services:

  postgres:
    image: postgres:16.3-alpine
    container_name: sdti-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: material
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: sdti-pgadmin
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@localhost.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 9090:80
    # volumes:
    #   - ./pgadmin:/var/lib/pgadmin

networks:
  default:
    name: sdti
    external: true